[package]
name = "tmlu-rs"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml = "0.8.10"
quick-xml = "0.31.0"

[dev-dependencies]
pretty_assertions = "1.1.0"
